# Generated by Django 5.0.1 on 2024-02-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cohort_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='imuser',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='imuser',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name='imuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imuser',
            name='user_type',
            field=models.CharField(choices=[('EIT', 'EIT'), ('TEACHING_FELLOW', 'TEACHING FELLOW'), ('ADMIN_STAFF', 'ADMINISTRATIVE STAFF'), ('ADMIN', 'ADMINSTRATOR')], default='EIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='users.cohort'),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
