# Generated by Django 5.0.1 on 2024-02-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model',
        ),
    ]
