# Generated by Django 5.0.1 on 2024-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_imuser_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imuser',
            name='permanent_login_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imuser',
            name='temporal_login_failed',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='imuser',
            name='temporal_signup_failed',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
