# Generated by Django 5.0.1 on 2024-02-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_cohort_imuser_cohortmember_cohort_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date_and_time', models.DateTimeField()),
                ('end_date_and_time', models.DateTimeField()),
                ('is_repeated', models.BooleanField(default=False)),
                ('repeat_frequency', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.CharField(max_length=50)),
                ('venue', models.TextField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date_and_time', models.DateTimeField()),
                ('end_date_and_time', models.DateTimeField()),
                ('is_repeated', models.BooleanField(default=False)),
                ('repeat_frequency', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.CharField(max_length=50)),
                ('venue', models.TextField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cohort')),
            ],
        ),
    ]
