# Generated by Django 5.0.1 on 2024-02-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
        ('users', '0005_imuser_date_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='main.course'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('CLASS_SESSION', 'Class Session'), ('WELLNESS_SESSION', 'Wellness Session'), ('GUEST_LECTURE', 'Guest Lecture')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule', to='users.cohort'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='repeat_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='venue',
            field=models.TextField(blank=True, max_length=225),
        ),
    ]
